config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaces do
    resources :reviews, only: [:new, :create, :destroy]
  end
  resources :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :space
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :space
  validates :content, presence: true
  validates :rating, inclusion: { in: 1..5 }
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name,
                  against: :name,
                  associated_against: {
                    user: :name
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]
  before_action :booking_params, only: %i[create update]

  def index
    @bookings = Booking.all
  end

  def show; end

  def new
    @booking = Booking.new
    @booking.user = current_user
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    authorize @booking

    if @booking.save
      flash.alert = 'Booking created successfully'
      redirect_to bookings_path
    else
      flash.alert = 'There was an error with your booking'
      render :new
    end
  end

  def edit; end

  def update
    if @booking.update(booking_params)
      flash.alert = 'Booking updated successfully'
      redirect_to bookings_path
    else
      flash.alert = 'There was an error updating your booking'
      render :edit
    end
  end

  def destroy
    if @booking.destroy
      flash.notice = 'Booking deleted successfully'
      redirect_to bookings_path
    else
      flash.notice = 'There was an error deleting your booking'
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:day, :space)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_space

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.space = @space
    if @review.save
      redirect_to space_path(@space)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to space_path(@space)
  end

  private

  def find_space
    @space = Space.find(params[:space_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: :show
  before_action :space_params, only: :create
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @spaces = Space.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @spaces = Space.geocoded
    end

    authorize @spaces

    @markers = @spaces.map do |space|
      {
        longitude: space.longitude,
        latitude: space.latitude,
        infoWindow: render_to_string(partial: "info_window", locals: { space: space })
      }
    end
  end

  def new
    @space = Space.new
  end

  def show
    # params.delete :query if params[:query].present?
  end

  def create
    @space = Space.new
    if @space.save
      redirect_to space_path(@space)
    else
      render :new
    end
  end

  def destroy
    @space.destroy
    redirect_to space_path(@space)
  end

  private

  def space_params
    params.require(:space).permit(:name, :address, :price, :number_of_desks)
  end

  def set_space
    @space = Space.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def featured_spaces
    @spaces = Space.all
    @random_spaces = @spaces.sample(3)
  end
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">

<%= simple_form_for @booking do |f| %>
 <div class="row justify-content-center"></div>
<%= f.association :user %>
 <div class="row justify-content-center"></div>
<%= f.association :space %>
 <div class="row justify-content-center"></div>
<%= f.input :day %>
 <div class="d-flex justify-content-center">
<%= f.submit "Update booking", class: "btn btn-outline-secondary" %>
</div>
<% end %>

   </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container my-3">
  <h2>Your upcoming bookings</h2>
  <% if @bookings.any? %>
    <div class="row">
      <% @bookings.each do |booking| %>
        <div class="card mx-3 my-3" style="width: 18rem;">
          <img class="card-image-size" src="<%= booking.space.photo %>" alt="<%= booking.space.name %>"/>
          <div class="card-body">
              
             <p><%= booking.day %> </p>
             <h5> <%= booking.space.name %> </h5>
             <p> Booking number <%= booking.id %> </p>
             <p><%= booking.space.address %> </p>
            
          </div>

           <div class="d-flex justify-content-around">
             
              <%= link_to "Update", edit_booking_path(booking), class: "btn btn-outline-secondary mb-2" %>
              <%= link_to "Delete", booking_path(booking), method: :delete,  data: { confirm: "Are you sure?" }, class: "btn btn-outline-secondary mb-2" %>

           </div>
        </div>
      <% end %>
    </div>
  <% else %>

  <div class="container w-50 p-3 mb-2 bg-light text-dark".bg-light>
    <p>You currently have no bookings!</p>
  <%= link_to 'Back to spaces list', spaces_path, class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

<div class="d-flex justify-content-center">
<%= link_to 'Back to spaces list', spaces_path, class: "btn btn-outline-secondary" %>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">

    <%= simple_form_for @booking do |f| %>
        <%# <div class="row justify-content-center"></div> %>
        <%# <%= f.association :user %>
        <div class="row justify-content-center"></div>
        <%= f.association :space %>
        <div class="row justify-content-center"></div>
        <%= f.input :day %>
        <div class="d-flex justify-content-center">
        <%= f.submit "Confirm booking", class: "btn btn-outline-secondary" %>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
  <h3> Here are the details of your booking number <%= @booking.id %> </h3>
  <h3> Date :  </h3>
  <h3> Space name : <%= @booking.space.name %> </h3>
  <h3> Space address : <%= @booking.space.name %> </h3>
  <h3> Price : <%= @booking.space.price %> </h3>
  <h3> Number of desks : <%= @booking.space.number_of_desks %> </h3>

  <%= link_to "Delete this booking", booking_path(@booking), method: :delete,  data: { confirm: "Are you sure?" } %>
  <br>
  <h5> If you want to change the booking details, click here: <%= link_to 'Make a change', new_booking_path(@booking) %> </h5>
 <br>
<%= link_to 'Back to bookings list', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeskDash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/58df6eefbf.js" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(354deg, rgba(179,174,238,0.6964986678265056) 0%, rgba(148,187,233,1) 100%), url('https://images.unsplash.com/photo-1524758631624-e2822e304c36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80')">

  <div class="containter overflow-hidden">

    <div class="row">
      <div class="col col-md-3"></div>
      <div class="col col-md-6 col-sm-10 text-white py-5">

        <h1 class="display-4">Welcome to Desk Dash</h1>
        <p class="lead">Find your the workspace that's right for you.</p>
        <p>We are proud to say we are the UK's leading provider in premium office co-working spaces. Start your day right and book a space with Desk-Dash today.</p>
        <hr class="my-4">

        <%= link_to spaces_path do %>
          <button class="btn btn-secondary" data-turbolinks="false">Find a space now</button>
        <% end %>

      </div>
      <div class="col col-md-3"></div>
    </div>

  </div>
</div>

<div class="container my-5">

  <div class="row align-items-center">
    <div class="col col-md-1"></div>

    <div class="col col-md-5 col-sm-10 my-5">

      <h2>Finding a better solution for office working</h2>
      <p>Desk-Dash is commited to offering a premuim office experience for those that need to travel, remote workers that want to have a dedicated working environement or for those who really just want to feel good when they work.</p>

      <% if !user_signed_in? %>
        <%= link_to new_user_session_path do %>
          <button class="btn btn-dark">Sign in</button>
        <% end %>
       <% else %>
       <%= link_to spaces_path do %>
          <button class="btn btn-outline-secondary" data-turbolinks="false">Explore available spaces</button>
       <% end %>
      <% end %>

    </div>

    <div class="col col-md-5 col-sm-10">

      <img src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1351&q=80"
           alt="happy offic people"
           width="100%"
           class="shadow rounded"
           >

    </div>

    <div class="col col-md-1"></div>

  </div>

  <hr>

  <div class="row align-items-center">

    <div class="col col-md-1"></div>

    <div class="col col-md-5 col-sm-10 my-5">

      <img src="https://images.unsplash.com/photo-1558959356-878a1a39e824?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80"
                alt="happy offic people"
                width="100%"
                class="shadow rounded"
              >

     </div>

    <div class="col col-md-5 col-sm-10 my-5">

      <h2>Safe workspaces for everyone</h2>
      <p>We are passionate about providing everyone with a safe working environemnt. We make it our mission to work with our partners to ensure all office spaces are cleaned and disinfected reguarly, provide sanitizers and always stock cleaning equimpent.</p>
      <p>Our premium partners also offer state fo the art ergonomic equimpent to help you stay as healthy as possible when you're working long hours.</p>

    </div>

     <div class="col col-md-1"></div>

  </div>

  <hr>

  <div class="row align-items-center">

    <div class="col col-md-1"></div>

    <div class="col col-sm-12 my-md-5">

      <h2 class="text-center">Featured work spaces</h2>

      <div class="d-flex justify-content-center my-3">
        <% featured_spaces.each do |space| %>

          <div class="card mx-md-3 mx-sm-1 mt-3" style="width: 18rem;">
            <img src="<%= space.photo %>%" class="card-img-top card-image-size image-large">
            <div class="card-body">
              <h5 class="card-title"><%= space.name %></h5>
              <%= link_to "More info", space_path(space), class: "btn btn-outline-secondary" %>

            </div>
          </div>

        <% end %>
    </div>

    </div>

    <div class="col col-md-1"></div>

  </div>

  <hr>

  <div class="row align-items-center">

    <div class="col col-md-1"></div>

    <div class="col col-sm-10 my-5">

    <h2 class="text-center">Premium work environments</h2>

    <div class="d-flex flex-column justify-content-center my-3">

      <div class="row mt-3">
        <div class="col col-2">
          <i class="fas fa-wifi" style="font-size: 50px"></i>
        </div>
        <div class="col">
          <p>The digital age is now, and fast, reliable internet is a necessity for most jobs these days. Therefore we strive to ensure that all the wrokspaces listed offer super fast fiber optice broadband included in your rental.</p>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col col-2">
          <i class="fas fa-mug-hot" style="font-size: 50px"></i>
        </div>
        <div class="col">
          <p>We know how important a good coffee is to start your day. Most of our partners offer some form of catering which is included in your rental, however if you work in a location that does not offer this, we will ensure that you get a free coffe on us!</p>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col col-2">
          <i class="fas fa-desktop" style="font-size: 50px"></i>
        </div>
        <div class="col">
          <p>We pride ourselves in offering work spaces to people from all sorts of backgrounds doing many all sorts of work. However one thing that is universally important no matter what ionudtry you work in is good screen equipment. We ensure that all our partner offer at least 1 external monitor and height adjustable office chair.</p>
        </div>
      </div>

      <div class="row mt-5 justify-content-center">
      <%= link_to spaces_path do %>
        <button class="btn btn-secondary" data-turbolinks="false">Book a space now</button>
      <% end %>
      </div>

    </div>

    </div>

    <div class="col col-md-1"></div>

  </div>

</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
    
    <%= simple_form_for [ @space, @review ] do |f| %>
    <div class="row justify-content-center"></div>
    <%= f.input :rating, collection: (1..5).to_a %>
    <div class="row justify-content-center"></div>
    <%= f.input :content %>
    <div class="row justify-content-center"></div>
    <%= f.submit "Submit review", class: 'btn btn-outline-secondary' %>
  <%= link_to space_path(@space[:id]) do %>
    <%= f.button :button, "Cancel", type: "reset", class: " btn btn-outline-secondary" %>
  <% end %>

<% end %>

    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="bg-dark text-white justify-content-center overflow-hidden sticky-bottom">

  <div class="row">
    <div class="col">
      <p class="text-center pt-3">
        Thank you for visiting
        <a href="https://github.com/benediktms/desk-dash" class="text-reset text-monospace text-danger">Desk-Dash</a>
        . Made with <i class="fas fa-heart text-danger"></i> by Local Response @
        <a href="https://www.lewagon.com/" class="text-reset text-monospace text-danger">Le Wagon</a>
      </p>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar d-flex justify-content-between sticky-top">

  <div class="p-2 bd-highlight text-white">
    <%= link_to root_path do %>
      <%= image_tag("desk-dash-logo.png", class: "logo") %>
    <% end %>
  </div>

  <div class="d-flex">

    <%= form_tag spaces_path, class: "form-inline my-2 my-lg-0 mr-3", method: :get do %>
      <%= text_field_tag :query,
                         params[:query],
                         class: "form-control mr-sm-2",
                         placeholder: "Search"
      %>
      <%= submit_tag "Search", class: "btn btn-outline-light my-2 my-sm-0" %>
    <% end %>

    <div class="p-1 bd-highlight dropdown">

      <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-circle text-white" style="font-size: 30px"></i>
      </button>

      <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="dropdownMenuButton">

        <% if user_signed_in? %>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <%= link_to 'View bookings', bookings_path, class: "dropdown-item" %>
          <a class="dropdown-item" href="#">Leave a review</a>
        <% else %>
          <%= link_to 'Sign in', new_user_session_path, class: "dropdown-item" %>
          <%= link_to 'Register', new_user_registration_path, class: "dropdown-item" %>
        <% end %>

      </div>

    </div>
  </div>

</nav>

app/views/spaces/_info_window.html.erb
<h2><%= space.name %></h2>
<p><%= space.address %></p>
<%= link_to "Check it out", space_path(space), class: "btn btn-outline-secondary btn-sm" %>

app/views/spaces/index.html.erb
<div id="space-index" class="container pt-2">
  <div class="row">

  <div class="container my-3 col-12 col-lg-4">
    <% if @spaces.any? %>
      <div class="row">
        <% @spaces.each do |space| %>

          <div class="card-product mx-3 my-3">
            <img src="<%= space.photo %>" alt="">
            <div class="card-product-infos">
              <h2><%= space.name %></h2>
              <p><%= space.price %></p>
              <%= link_to "Check it out", space_path(space), class: "btn btn-outline-secondary btn-sm" %>
            </div>
          </div>

        <% end %>

      </div>
    <% else %>
      <p>There are no spaces available!</p>
    <% end %>
  </div>

    <div class="col-12 col-lg-8 ">
      <div id="map"
           data-markers="<%= @markers.to_json %>"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
 </div>
</div>

app/views/spaces/new.html.erb
<%= simple_form_for @space do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :price %>
<%= f.input :number_of_desks %>
<%= f.submit "Confirm space creation", class: "btn btn-primary" %>
<% end %>

app/views/spaces/show.html.erb
<div class="banner" style="background-image: url(<%= @space.photo %>)"></div>

  <div class="container">

  <div class="row justify-content-center px-3">

    <div class="col-md-8 col-sm-10">

      <div class="row">
        <h1 class="py-5"><%= @space.name %></h1>
      </div>

      <div class="row">

        <h2>Information:</h2>
      </div>

      <div class="row align-items-center">
        <div class="col">
          <div class="card mt-3 mb-5">
            <div class="card-body">
              <div class="card-text">
                <p>Price: <i class="fas"></i><%= @space.price %></p>
                <p>Desks available: <%= @space.number_of_desks %></p>
                <p><%= @space.address %></p>
              </div>
            </div>
          </div>
        </div>

      </div>


      <div class="d-flex flex-column mt-3 mb-5">


        <div class="row mt-3 align-items-center">
          <div class="col col-2">
            <i class="fas fa-door-open" style="font-size: 50px"></i>
          </div>
          <div class="col">
            <h4>Open door</h4>
            <p>This office has an open door policy which means you can coem and go as you please! You may be asked to present a booking confirmation when you arrive.</p>
          </div>
        </div>

        <div class="row mt-3 align-items-center">
          <div class="col col-2">
            <i class="fas fa-hand-sparkles" style="font-size: 50px;"></i>
          </div>
          <div class="col">
            <h4>Good hygiene standards</h4>
            <p>This work space is in compliance with social distancing measures and governemtn advised hygiene standards. Hand sanitizer and other measures will be provided on site at all times.</p>
          </div>
        </div>

        <div class="row mt-3 align-items-center">
          <div class="col col-2">
            <i class="far fa-calendar-alt" style="font-size: 50px"></i>
          </div>
          <div class="col">
            <h4>Cancellation policy</h4>
            <p>You can cancel your booking up to 24h before your booking date.</p>
          </div>
        </div>

        <% if @space.fiber_optic %>
          <div class="row mt-3 align-items-center">
            <div class="col col-2">
              <i class="fas fa-wifi" style="font-size: 50px"></i>
            </div>
            <div class="col">
              <h4>Super fast Fiber Optic connection</h4>
              <p>This work space offers guaranteed fiber optic connection to supercharge your workflow!</p>
            </div>
          </div>
        <% end %>

        <% if @space.catering %>
          <div class="row mt-3 align-items-center">
            <div class="col col-2">
              <i class="fas fa-mug-hot" style="font-size: 50px"></i>
            </div>
            <div class="col">
              <h4>Catering</h4>
              <p>This work space has included free catering wehn you book your slot! Usualyl this means that you'll get all-you-can drink coffee, but you may get other goodies too depending on your booking!</p>
            </div>
          </div>
        <% end %>

<!--        <div class="row mt-3 align-items-center">-->
<!--          <div class="col">-->
<!--            <h4>See what others have said about this space</h4>-->
            <%# @space.reviews.each do |review| %>
<!--              <p><%#=review.content %></p>-->
              <%#= link_to 'Delete', space_review_path(@space[:id], review), method: :delete %>
<!--              <hr>-->
            <%# end %>
<!--          </div>-->
<!--        </div>-->

      </div>

      <div class="row">
          <%= link_to "Book this space", new_booking_path, class: "btn btn-secondary mr-3" %>
          <%= link_to spaces_path do %>
            <button class="btn btn-outline-secondary">Back to spaces</button>
          <% end %>

      </div>

      <div class="row pt-5 flex-column">

        <h2>See what others are saying about this work space</h2>
        <%= link_to "Add a review", new_space_review_path(@space), class: "mb-3" %>


        <div class="d-felx mb-5">
          <% @space.reviews.each do |review| %>
            <div class="review-content p-3 shadow my-4">
              <% review.rating.to_i.times do %>
                <span class="fa fa-star checked"></span>
              <% end %>
              <p><%=review.content %></p>
            </div>
            <%#= link_to 'Delete', space_review_path(@space[:id], review), method: :delete %>
<!--            <hr>-->
          <% end %>
        </div>

      </div>

    </div>

  </div>

</div>